import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/global/globals.css";

// import { getServerSession } from "next-auth";

// import AuthProvider from "./components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`${inter.className} p-6`}>
        {/* <AuthProvider session={session}>{children}</AuthProvider> */}
        {children}
      </body>
    </html>
  );
}
